In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('../cleaning/cleaned_restaurant_reviews.csv', index_col=0).reset_index(drop=True)
data.head(2)

,url,name,neighbourhood,price,categories,review,user,date,cleaned_price,cleaned_categories,...,Western,Supper,Japanese,Healthy,Fast Food,Value,Halal,Korean,Sustainable,region
0,https://www.burpple.com/bedok-85-market?bp_ref...,85 Fengshan Centre,Bedok,~$5/pax,"['Hawker Food', 'Supper', 'Cheap & Good']","\nFish Ball Minced Meat Noodle\nFishball, meat...",Triffany Lim,21m ago,5.0,"['Local Delights', 'Supper', 'Value']",...,0,1,0,0,0,1,0,0,0,East
1,https://www.burpple.com/bedok-85-market?bp_ref...,85 Fengshan Centre,Bedok,~$5/pax,"['Hawker Food', 'Supper', 'Cheap & Good']","\nOrh lua\nThere are a couple of stores, but g...",Ally Tan,Jul 30 at 4:12pm,5.0,"['Local Delights', 'Supper', 'Value']",...,0,1,0,0,0,1,0,0,0,East

In [4]:
# concatenate all the reviews for each restaurant
restaurant_review_df = data[['url', 'cleaned_text']]
restaurant_review_df = restaurant_review_df.groupby(['url'], as_index = False).agg({'cleaned_text': ' '.join})
restaurant_review_df.head(5)

,url,cleaned_text
0,https://www.burpple.com/108-matcha-saro?bp_ref...,s850 strong matcha flavor soft serve topped wh...
1,https://www.burpple.com/136-hong-kong-street-f...,zhi char feast family love tze char lose count...
2,https://www.burpple.com/15-stamford?bp_ref=%2F...,four hand dinner chef alvin chef jay legendary...
3,https://www.burpple.com/25-degrees-singapore?b...,oh yesh loveeeee burger goooooood locate hotel...
4,https://www.burpple.com/46-mittsu?bp_ref=%2Ff%...,signature firebird koreaninspired sandwich fry...

In [5]:
restaurant_characteristics_df = data.drop(['review', 'cleaned_text'], axis=1)
restaurant_characteristics_df = restaurant_characteristics_df.groupby(['url'], as_index = False).first()
restaurant_characteristics_df.head(2)

,url,name,neighbourhood,price,categories,user,date,cleaned_price,cleaned_categories,Chinese,...,Western,Supper,Japanese,Healthy,Fast Food,Value,Halal,Korean,Sustainable,region
0,https://www.burpple.com/108-matcha-saro?bp_ref...,108 Matcha Saro (Suntec City),Promenade,~$10/pax,"['Desserts', 'Ice Cream & Yoghurt', 'Japanese']",Stefanny Stefanny,Nov 8 at 3:09pm,10.0,"['Desserts', 'Desserts', 'Japanese']",0,...,0,0,1,0,0,0,0,0,0,South
1,https://www.burpple.com/136-hong-kong-street-f...,136 Hong Kong Street Fish Head Steamboat (Joo ...,Macpherson,~$15/pax,"['Rainy Day Comforts', 'Hawker Food', 'Hot Pot...",Spoons Of Delights,3h ago,15.0,"['Rainy Day Comforts', 'Local Delights', 'Chin...",1,...,0,0,0,0,0,0,0,0,0,East

In [6]:
restaurant_review_df = pd.merge(restaurant_review_df, restaurant_characteristics_df, on='url')

In [7]:
restaurant_review_df.to_csv('concat_reviews_by_restaurant.csv')